# Generated by Django 5.0.2 on 2024-02-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="total_downloads",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
