# Generated by Django 5.0.2 on 2024-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_uploadedfile_total_downloads"),
    ]

    operations = [
        migrations.CreateModel(
            name="muslimNmaes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("females", models.JSONField(blank=True, null=True)),
                ("males", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
