# Generated by Django 5.0.2 on 2024-02-25 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_muslimnmaes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="muslimNmaes",
            new_name="muslimNames",
        ),
    ]
